on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

name: Build Dockerhub Images

jobs:
  build:
    name: build_dockerhub_images
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [ '7.1' ]

    steps:
      - name: php version
        run: |
          REP_VERSION=${{ github.ref }}
          TAG=${REP_VERSION#refs/tags/}
          echo $TAG
          ls -al

      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            PHP_VERSION=${{ matrix.php }}
          push: true
          tags: "netcommons3/nc3app-php${{ matrix.php }}:latest"

      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
