on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

name: Build Dockerhub Images

jobs:
  build:
    name: build_dockerhub_images
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4' ]

    steps:
      - uses: actions/checkout@v2

      - name: Slack Notification on Start
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASE }}
          SLACK_CHANNEL: notify-nc3-release
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_COLOR: "#f0ad4e"
          SLACK_MESSAGE: "Start Job"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            PHP_VERSION=${{ matrix.php }}
          push: true
          tags: "netcommons3/nc3app-php${{ matrix.php }}:latest"

      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}

      # JOB成功時はこちらのステップが実行される
      - name: Slack Notification on Finish
        uses: rtCamp/action-slack-notify@v2.2.0
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASE }}
          SLACK_CHANNEL: notify-nc3-release
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_COLOR: good
          SLACK_MESSAGE: "Job Success"

      # JOB失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.2.0
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASE }}
          SLACK_CHANNEL: notify-nc3-tests
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_COLOR: danger
          SLACK_MESSAGE: "Job Failure"
