on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

name: Build Dockerhub Images

jobs:
  start:
    name: start
    runs-on: ubuntu-18.04
    steps:
      - name: Slack Notification on Start
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASE }}
          SLACK_CHANNEL: notify-nc3-release
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_COLOR: "#f0ad4e"
          SLACK_MESSAGE: "Start Job"

  build:
    name: build
    runs-on: ubuntu-18.04
    needs: start
    strategy:
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4' ]

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}
            PHP_VERSION=${{ matrix.php }}
          push: true
          tags: "netcommons3/nc3app-php${{ matrix.php }}:latest"

      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}

      # JOB失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.2.0
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASE }}
          SLACK_CHANNEL: notify-nc3-release
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_COLOR: danger
          SLACK_MESSAGE: "Job Failure"

      # JOBキャンセル時はこちらのステップが実行される
      - name: Slack Notification on Canceled
        uses: rtCamp/action-slack-notify@v2.2.0
        if: cancelled()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASE }}
          SLACK_CHANNEL: notify-nc3-release
          SLACK_TITLE: "${{ github.repository }}(php${{ matrix.php }})"
          SLACK_COLOR: #eeeeee
          SLACK_MESSAGE: "Job Canceled"

  finish:
    name: finish
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "Docker Image ${{ github.ref }} released."
          draft: false
          prerelease: false

      # JOB成功時はこちらのステップが実行される
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASE }}
          SLACK_CHANNEL: notify-nc3-release
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_COLOR: good
          SLACK_MESSAGE: "Job Success"
